insert into Student (Permissions, NetID, FirstName, LastName, email, Password) values (0, 'abc123000','Alen', 'Carl', 'abc123000@utdallas.edu','password123'); 
insert into Student (Permissions, NetID, FirstName, LastName, email, Password) values (0,'def456000','Dylan','Ford','def456000@utdallas.edu','password456');
insert into Student (Permissions, NetID, FirstName, LastName, email, Password) values (0,'ghi789000','Grant','ink','ghi789@utdallas.edu', 'password789');
insert into Student (Permissions, NetID, FirstName, LastName, email, Password) values (0,'jkl000123','Justin','land','jkl000123@utdallas.edu','password0123');
insert into Student (Permissions, NetID, FirstName, LastName, email, Password) values (1,'mno000456', 'Morgan', 'Owens', 'mno00456@utdallas.edu', 'password0456');
insert into Student (Permissions, NetID, FirstName, LastName, email, Password) values (0,'pqr000789', 'Peter', 'Ronald', 'pqr000789@utdallas.edu','password0789');
insert into Professor (ProfessorNetID, FirstName, LastName, email, Password) values ('sxa173731', 'Sridhar','Alagar',' sxa173731@utdallas.edu', 'password1737');
insert into Professor (ProfessorNetID, FirstName, LastName, email, Password) values ('mcl123456', 'Mariana','Larson','mcl123456@utdallas.edu','password123456');
insert into Class (ClassName, ClassID, sectionNumber,Size, Professor_ProfessorNetID, ClassNumber) values ('Systems Programming in UNIX and Other Environments', 24313, 505,10,'sxa173731', 'CS3377');
insert into Class (ClassName, ClassID, sectionNumber,Size, Professor_ProfessorNetID, ClassNumber) values ('The Oceans', 75822, 501,50,'mcl123456', 'ISNS2367');
insert into Enrollment (Student_NetID,Class_ClassID) values ('abc123000', 24313);
insert into Enrollment (Student_NetID,Class_ClassID) values ('def456000', 24313);
insert into Enrollment (Student_NetID,Class_ClassID) values ('ghi789000', 24313);
insert into Enrollment (Student_NetID,Class_ClassID) values ('jkl000123', 24313);
insert into Enrollment (Student_NetID,Class_ClassID) values ('ghi789000', 75822);
insert into Enrollment (Student_NetID,Class_ClassID) values ('jkl000123', 75822);
insert into Enrollment (Student_NetID,Class_ClassID) values ('mno000456', 75822);
insert into Enrollment (Student_NetID,Class_ClassID) values ('pqr000789', 75822);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a1-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a1-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a2-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a2-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a3-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a3-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a4-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a4-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a5-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a5-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a6-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a6-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a7-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a7-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a8-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a8-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a9-3377','.docx', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a9-3377.docx"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('a10-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\a10-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('p1-3377','.pdf', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\p1-3377.pdf"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('p2-3377','.pdf', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\p2-3377.pdf"),24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('p3-3377','.txt', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\p3-3377.txt"), 24313);
insert into file (FileName, FileType, FileContent, Class_ClassID) values ('Syllabus 3377.007 F22','.pdf', load_file("C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Syllabus 3377.007 F22.pdf"), 24313);
Insert into thread (Class_ClassID,CreationDate,ThreadContent,Student_NetID, ThreadTitle) values (24313, Now(), 'When is assignment 1 due?', 'abc123000', 'A1 due date');
Insert into thread (Class_ClassID,CreationDate,ThreadContent,Student_NetID, ThreadTitle) values (24313, Now(), 'When is the first exam?', 'ghi789000', 'Exam 1 due date');
Insert into thread (Class_ClassID,CreationDate,ThreadContent,Student_NetID, ThreadTitle) values (24313, Now(), 'Can we use C++ for the projects?', 'pqr000789', 'C++ projects');
insert into reply (Thread_ThreadID, CreationDate, Content,Student_NetID) values (1, Now(), 'it is due on january 26th at midnight', 'mno000456');
insert into reply (Thread_ThreadID, CreationDate, Content,Student_NetID) values (3, Now(), 'I think we can but we should probably ask to make sure', 'jkl000123');
insert into reply (Thread_ThreadID, CreationDate, Content,Student_NetID) values (3, Now(), 'We have to use C, it is in the syllabus.', 'def456000');


